package main

var (
	gameQuests = []Quest{
		{Name: "Goblin Slayer", Description: "Kill 10 goblins", Requirements: map[string]int{"Goblin": 10}, Reward: 100},
		{Name: "Rat Catcher", Description: "Kill 5 rats", Requirements: map[string]int{"Rat": 5}, Reward: 50},
		{Name: "Rat Finder", Description: "Kill 1 rat", Requirements: map[string]int{"Rat": 1}, Reward: 10},
		{Name: "Wolf Finder", Description: "Kill 1 wolf", Requirements: map[string]int{"Wolf": 1}, Reward: 10},
		{Name: "Scorpion Finder", Description: "Kill 1 scorpion", Requirements: map[string]int{"Scorpion": 1}, Reward: 10},
		{Name: "Rat Dominator", Description: "Kill 8 rats", Requirements: map[string]int{"Rat": 8}, Reward: 80},
		{Name: "Bear Hunter", Description: "Kill 2 bears", Requirements: map[string]int{"Bear": 2}, Reward: 30},
		{Name: "Zombie Eliminator", Description: "Kill 6 zombies", Requirements: map[string]int{"Zombie": 6}, Reward: 60},
		{Name: "Ogre Exterminator", Description: "Kill 1 ogre", Requirements: map[string]int{"Ogre": 1}, Reward: 40},
		{Name: "Wyvern Tamer", Description: "Kill 1 wyvern", Requirements: map[string]int{"Wyvern": 1}, Reward: 70},
		{Name: "Serpent Slayer", Description: "Kill 4 serpents", Requirements: map[string]int{"Serpent": 4}, Reward: 40},
		{Name: "Halfling Harasser", Description: "Kill 3 halflings", Requirements: map[string]int{"Halfling": 3}, Reward: 45},
		{Name: "Spider Smasher", Description: "Kill 7 spiders", Requirements: map[string]int{"Spider": 7}, Reward: 70},
		{Name: "Scorpion Scorcher", Description: "Kill 5 scorpions", Requirements: map[string]int{"Scorpion": 5}, Reward: 50},
		{Name: "Bear Brute", Description: "Kill 4 bears", Requirements: map[string]int{"Bear": 4}, Reward: 80},
		{Name: "Zombie Zapper", Description: "Kill 10 zombies", Requirements: map[string]int{"Zombie": 10}, Reward: 100},
		{Name: "Ogre Overthrower", Description: "Kill 2 ogres", Requirements: map[string]int{"Ogre": 2}, Reward: 120},
		{Name: "Wyvern Warrior", Description: "Kill 3 wyverns", Requirements: map[string]int{"Wyvern": 3}, Reward: 210},
		{Name: "Serpent Subduer", Description: "Kill 6 serpents", Requirements: map[string]int{"Serpent": 6}, Reward: 120},
		{Name: "Intrepid Hunter", Description: "Kill 1 of each enemy type", Requirements: map[string]int{"Goblin": 1, "Rat": 1, "Wolf": 1, "Halfling": 1, "Spider": 1, "Scorpion": 1, "Bear": 1, "Zombie": 1, "Ogre": 1, "Wyvern": 1, "Serpent": 1}, Reward: 500},
		{Name: "Giant Hunter", Description: "Kill 2 giants", Requirements: map[string]int{"Giant": 2}, Reward: 150},
		{Name: "Skeleton Smasher", Description: "Kill 6 skeletons", Requirements: map[string]int{"Skeleton": 6}, Reward: 75},
		{Name: "Vampire Vanquisher", Description: "Kill 3 vampires", Requirements: map[string]int{"Vampire": 3}, Reward: 200},
		{Name: "Ghost Buster", Description: "Kill 4 ghosts", Requirements: map[string]int{"Ghost": 4}, Reward: 120},
		{Name: "Master Hunter", Description: "Kill 2 of each enemy type", Requirements: map[string]int{"Goblin": 2, "Rat": 2, "Wolf": 2, "Halfling": 2, "Spider": 2, "Scorpion": 2, "Bear": 2, "Zombie": 2, "Ogre": 2, "Wyvern": 2, "Serpent": 2, "Giant": 2, "Skeleton": 2, "Vampire": 2, "Ghost": 2}, Reward: 1000},
		{Name: "Goblin Horde", Description: "Kill 25 goblins", Requirements: map[string]int{"Goblin": 25}, Reward: 250},
		{Name: "Rat Infestation", Description: "Kill 15 rats", Requirements: map[string]int{"Rat": 15}, Reward: 150},
		{Name: "Wolves' Den", Description: "Kill 12 wolves", Requirements: map[string]int{"Wolf": 12}, Reward: 120},
		{Name: "Bane of Halflings", Description: "Kill 8 halflings", Requirements: map[string]int{"Halfling": 8}, Reward: 160},
		{Name: "Spider Exterminator", Description: "Kill 30 spiders", Requirements: map[string]int{"Spider": 30}, Reward: 300},
		{Name: "Scorpion King", Description: "Kill 18 scorpions", Requirements: map[string]int{"Scorpion": 18}, Reward: 180},
		{Name: "Grizzly Encounter", Description: "Kill 5 bears", Requirements: map[string]int{"Bear": 5}, Reward: 100},
		{Name: "Zombie Apocalypse", Description: "Kill 40 zombies", Requirements: map[string]int{"Zombie": 40}, Reward: 400},
		{Name: "Ogre's Bane", Description: "Kill 6 ogres", Requirements: map[string]int{"Ogre": 6}, Reward: 240},
		{Name: "Wyvern's Demise", Description: "Kill 5 wyverns", Requirements: map[string]int{"Wyvern": 5}, Reward: 350},
		{Name: "Serpent's End", Description: "Kill 10 serpents", Requirements: map[string]int{"Serpent": 10}, Reward: 250},
		{Name: "Giant Trouble", Description: "Kill 3 giants", Requirements: map[string]int{"Giant": 3}, Reward: 450},
		{Name: "Skeleton Army", Description: "Kill 20 skeletons", Requirements: map[string]int{"Skeleton": 20}, Reward: 200},
		{Name: "Vampire Hunter", Description: "Kill 7 vampires", Requirements: map[string]int{"Vampire": 7}, Reward: 490},
		{Name: "Ghost Whisperer", Description: "Kill 9 ghosts", Requirements: map[string]int{"Ghost": 9}, Reward: 270},
		{Name: "Monster Mash", Description: "Kill 5 of each enemy type", Requirements: map[string]int{"Goblin": 5, "Rat": 5, "Wolf": 5, "Halfling": 5, "Spider": 5, "Scorpion": 5, "Bear": 5, "Zombie": 5, "Ogre": 5, "Wyvern": 5, "Serpent": 5, "Giant": 5, "Skeleton": 5, "Vampire": 5, "Ghost": 5}, Reward: 2500},
		{Name: "Goblin Overlord", Description: "Kill 50 goblins", Requirements: map[string]int{"Goblin": 50}, Reward: 500},
		{Name: "Rat Eradicator", Description: "Kill 30 rats", Requirements: map[string]int{"Rat": 30}, Reward: 300},
		{Name: "Alpha Wolf", Description: "Kill 20 wolves", Requirements: map[string]int{"Wolf": 20}, Reward: 200},
		{Name: "Halfling Nightmare", Description: "Kill 15 halflings", Requirements: map[string]int{"Halfling": 15}, Reward: 225},
		{Name: "Arachnid Annihilator", Description: "Kill 50 spiders", Requirements: map[string]int{"Spider": 50}, Reward: 500},
		{Name: "Scorpion Slayer", Description: "Kill 25 scorpions", Requirements: map[string]int{"Scorpion": 25}, Reward: 250},
		{Name: "Bear Whisperer", Description: "Kill 10 bears", Requirements: map[string]int{"Bear": 10}, Reward: 200},
		{Name: "Zombie Conqueror", Description: "Kill 60 zombies", Requirements: map[string]int{"Zombie": 60}, Reward: 600},
		{Name: "Ogre Slayer", Description: "Kill 10 ogres", Requirements: map[string]int{"Ogre": 10}, Reward: 400},
		{Name: "Wyvern Master", Description: "Kill 8 wyverns", Requirements: map[string]int{"Wyvern": 8}, Reward: 560},
		{Name: "Serpentbane", Description: "Kill 15 serpents", Requirements: map[string]int{"Serpent": 15}, Reward: 375},
		{Name: "Giant's Demise", Description: "Kill 5 giants", Requirements: map[string]int{"Giant": 5}, Reward: 750},
		{Name: "Skeleton Crusher", Description: "Kill 35 skeletons", Requirements: map[string]int{"Skeleton": 35}, Reward: 350},
		{Name: "Vampire's Bane", Description: "Kill 10 vampires", Requirements: map[string]int{"Vampire": 10}, Reward: 700},
		{Name: "Ghost Vanisher", Description: "Kill 15 ghosts", Requirements: map[string]int{"Ghost": 15}, Reward: 450},
		{Name: "Creature Collector", Description: "Kill 10 of each enemy type", Requirements: map[string]int{"Goblin": 10, "Rat": 10, "Wolf": 10, "Halfling": 10, "Spider": 10, "Scorpion": 10, "Bear": 10, "Zombie": 10, "Ogre": 10, "Wyvern": 10, "Serpent": 10, "Giant": 10, "Skeleton": 10, "Vampire": 10, "Ghost": 10}, Reward: 5000},
		{Name: "Goblin General", Description: "Kill 100 goblins", Requirements: map[string]int{"Goblin": 100}, Reward: 1000},
		{Name: "Wolf Pack Leader", Description: "Kill 30 wolves", Requirements: map[string]int{"Wolf": 30}, Reward: 300},
		{Name: "Halfling Hinderer", Description: "Kill 20 halflings", Requirements: map[string]int{"Halfling": 20}, Reward: 300},
		{Name: "Arachnid Eliminator", Description: "Kill 75 spiders", Requirements: map[string]int{"Spider": 75}, Reward: 750},
		{Name: "Scorpion Dominator", Description: "Kill 40 scorpions", Requirements: map[string]int{"Scorpion": 40}, Reward: 400},
		{Name: "Bear Wrestler", Description: "Kill 20 bears", Requirements: map[string]int{"Bear": 20}, Reward: 400},
		{Name: "Zombie Overlord", Description: "Kill 80 zombies", Requirements: map[string]int{"Zombie": 80}, Reward: 800},
		{Name: "Ogre Breaker", Description: "Kill 15 ogres", Requirements: map[string]int{"Ogre": 15}, Reward: 600},
		{Name: "Wyvern Lord", Description: "Kill 12 wyverns", Requirements: map[string]int{"Wyvern": 12}, Reward: 840},
		{Name: "Serpent Extinguisher", Description: "Kill 25 serpents", Requirements: map[string]int{"Serpent": 25}, Reward: 625},
		{Name: "Giant Slayer", Description: "Kill 10 giants", Requirements: map[string]int{"Giant": 10}, Reward: 1500},
		{Name: "Skeleton Destroyer", Description: "Kill 50 skeletons", Requirements: map[string]int{"Skeleton": 50}, Reward: 500},
		{Name: "Vampire Nemesis", Description: "Kill 15 vampires", Requirements: map[string]int{"Vampire": 15}, Reward: 1050},
		{Name: "Ghost Evictor", Description: "Kill 20 ghosts", Requirements: map[string]int{"Ghost": 20}, Reward: 600},
		{Name: "Champion Hunter", Description: "Kill 20 of each enemy type", Requirements: map[string]int{"Goblin": 20, "Rat": 20, "Wolf": 20, "Halfling": 20, "Spider": 20, "Scorpion": 20, "Bear": 20, "Zombie": 20, "Ogre": 20, "Wyvern": 20, "Serpent": 20, "Giant": 20, "Skeleton": 20, "Vampire": 20, "Ghost": 20}, Reward: 10000},
		{Name: "Goblin Suppressor", Description: "Kill 200 goblins", Requirements: map[string]int{"Goblin": 200}, Reward: 2000},
		{Name: "Rat Extinguisher", Description: "Kill 100 rats", Requirements: map[string]int{"Rat": 100}, Reward: 1000},
		{Name: "Wolf Alpha", Description: "Kill 50 wolves", Requirements: map[string]int{"Wolf": 50}, Reward: 500},
		{Name: "Halfling Warden", Description: "Kill 30 halflings", Requirements: map[string]int{"Halfling": 30}, Reward: 450},
		{Name: "Arachnid Devastator", Description: "Kill 100 spiders", Requirements: map[string]int{"Spider": 100}, Reward: 1000},
		{Name: "Rat Plague", Description: "Kill 60 rats", Requirements: map[string]int{"Rat": 60}, Reward: 600},
		{Name: "Imp Hunter", Description: "Kill 3 Imps", Requirements: map[string]int{"Imp": 3}, Reward: 50},
		{Name: "Werewolf Rampage", Description: "Kill 5 Werewolves", Requirements: map[string]int{"Werewolf": 5}, Reward: 75},
		{Name: "Gargoyle Extermination", Description: "Kill 2 Gargoyles", Requirements: map[string]int{"Gargoyle": 2}, Reward: 40},
		{Name: "Medusa's Curse", Description: "Defeat Medusa", Requirements: map[string]int{"Medusa": 1}, Reward: 500},
		{Name: "Troll Trouble", Description: "Kill 3 Trolls", Requirements: map[string]int{"Troll": 3}, Reward: 100},
		{Name: "Krack Attack", Description: "Kill the Kraken", Requirements: map[string]int{"Kraken": 1}, Reward: 1000},
		{Name: "Basilisk Slayer", Description: "Kill 4 Basilisks", Requirements: map[string]int{"Basilisk": 4}, Reward: 150},
		{Name: "Chimera Hunt", Description: "Kill the Chimera", Requirements: map[string]int{"Chimera": 1}, Reward: 750},
		{Name: "Mummy's Curse", Description: "Defeat the Mummy", Requirements: map[string]int{"Mummy": 1}, Reward: 400},
		{Name: "Lich Takedown", Description: "Kill the Lich", Requirements: map[string]int{"Lich": 1}, Reward: 800},
		{Name: "Wraith Banishment", Description: "Kill 3 Wraiths", Requirements: map[string]int{"Wraith": 3}, Reward: 200},
		{Name: "Zombie Dragon Slaying", Description: "Kill the Zombie Dragon", Requirements: map[string]int{"Zombie Dragon": 1}, Reward: 1500},
		{Name: "Specter Hunt", Description: "Kill 5 Specters", Requirements: map[string]int{"Specter": 5}, Reward: 250},
		{Name: "Animated Armor Elimination", Description: "Kill 2 Animated Armors", Requirements: map[string]int{"Animated Armor": 2}, Reward: 100},
		{Name: "Shadow Extermination", Description: "Kill 4 Shadows", Requirements: map[string]int{"Shadow": 4}, Reward: 300},
		{Name: "Ghoul Slaughter", Description: "Kill 3 Ghouls", Requirements: map[string]int{"Ghoul": 3}, Reward: 150},
		{Name: "Cave Troll Extermination", Description: "Kill 2 Cave Trolls", Requirements: map[string]int{"Cave Troll": 2}, Reward: 100},
		{Name: "Harpy Invasion", Description: "Kill 5 Harpies", Requirements: map[string]int{"Harpy": 5}, Reward: 125},
		{Name: "Winged Demon Slaying", Description: "Kill 2 Demons", Requirements: map[string]int{"Demon": 2}, Reward: 200},
		{Name: "Minotaur Conquest", Description: "Kill the Minotaur", Requirements: map[string]int{"Minotaur": 1}, Reward: 600},
		{Name: "Ghost Hunter", Description: "Kill 4 Ghosts", Requirements: map[string]int{"Ghost": 4}, Reward: 200},
		{Name: "Imp Hunter", Description: "Kill 3 imps", Requirements: map[string]int{"Imp": 3}, Reward: 200},
		{Name: "Harpy Slayer", Description: "Kill 5 harpies", Requirements: map[string]int{"Harpy": 5}, Reward: 350},
		{Name: "Werewolf Hunt", Description: "Kill 2 werewolves", Requirements: map[string]int{"Werewolf": 2}, Reward: 300},
		{Name: "Minotaur's Labyrinth", Description: "Find and defeat the Minotaur", Requirements: map[string]int{"Minotaur": 1}, Reward: 1000},
		{Name: "Gargoyle Cleanup", Description: "Kill 7 gargoyles", Requirements: map[string]int{"Gargoyle": 7}, Reward: 500},
		{Name: "Medusa's Curse", Description: "Defeat Medusa and break her curse on the town", Requirements: map[string]int{"Medusa": 1}, Reward: 1500},
		{Name: "Troll Trouble", Description: "Find and slay the troll terrorizing the village", Requirements: map[string]int{"Troll": 1}, Reward: 800},
		{Name: "Mummy's Tomb", Description: "Retrieve a valuable artifact from the mummy's tomb", Requirements: map[string]int{"Mummy": 1}, Reward: 1200},
		{Name: "Kraken Hunt", Description: "Slay the kraken threatening ships in the harbor", Requirements: map[string]int{"Kraken": 1}, Reward: 2000},
		{Name: "Basilisk Hunter", Description: "Find and kill the basilisk before it turns anyone else to stone", Requirements: map[string]int{"Basilisk": 1}, Reward: 900},
		{Name: "Demon's Lair", Description: "Enter the demon's lair and defeat its minions", Requirements: map[string]int{"Demon": 5}, Reward: 2500},
		{Name: "Chimera Hunt", Description: "Hunt down the chimera and save the village from its destruction", Requirements: map[string]int{"Chimera": 1}, Reward: 1800},
		{Name: "Wraith Exorcism", Description: "Banish the wraith that is haunting the graveyard", Requirements: map[string]int{"Wraith": 1}, Reward: 700},
		{Name: "Lich's Domain", Description: "Enter the lich's domain and retrieve the stolen artifact", Requirements: map[string]int{"Lich": 1}, Reward: 3000},
		{Name: "Zombie Dragon Slaying", Description: "Slay the zombie dragon that is terrorizing the countryside", Requirements: map[string]int{"Zombie Dragon": 1}, Reward: 3500},
		{Name: "Cave Troll's Lair", Description: "Navigate the treacherous cave and defeat the cave troll", Requirements: map[string]int{"Cave Troll": 1}, Reward: 1000},
		{Name: "Specter Banishing", Description: "Banish the specter haunting the abandoned mansion", Requirements: map[string]int{"Specter": 1}, Reward: 1500},
		{Name: "Animated Armor Ambush", Description: "Survive the ambush of animated armors and destroy their source", Requirements: map[string]int{"Animated Armor": 5}, Reward: 2000},
		{Name: "Harpy Hunt", Description: "Kill 3 Harpies", Requirements: map[string]int{"Harpy": 3}, Reward: 400},
		{Name: "The Werewolf's Den", Description: "Kill 5 Werewolves", Requirements: map[string]int{"Werewolf": 5}, Reward: 750},
		{Name: "Minotaur's Labyrinth", Description: "Navigate and Kill the Minotaur in its Labyrinth", Requirements: map[string]int{"Minotaur": 1}, Reward: 1200},
		{Name: "The Stone Gargoyle", Description: "Defeat the Gargoyle, a monster carved out of stone", Requirements: map[string]int{"Gargoyle": 1}, Reward: 800},
		{Name: "The Gorgon's Curse", Description: "Defeat the Medusa, a Gorgon whose gaze can turn you to stone", Requirements: map[string]int{"Medusa": 1}, Reward: 1000},
		{Name: "Troll Bridge", Description: "Defeat the troll guarding the bridge", Requirements: map[string]int{"Troll": 1}, Reward: 900},
		{Name: "Mummy's Tomb", Description: "Retrieve a valuable artifact from the Mummy's Tomb", Requirements: map[string]int{"Mummy": 1}, Reward: 1200},
		{Name: "Kraken's Lair", Description: "Explore the deep waters and kill the Kraken, a giant sea monster", Requirements: map[string]int{"Kraken": 1}, Reward: 1500},
		{Name: "Basilisk Hunt", Description: "Hunt and kill the Basilisk, a monster whose gaze can petrify you", Requirements: map[string]int{"Basilisk": 1}, Reward: 1000},
		{Name: "Demon Summoning", Description: "Find and close the portal to the demon realm, preventing more demons from entering our world", Requirements: map[string]int{"Demon": 5}, Reward: 5000},
		{Name: "Chimera Hunt", Description: "Hunt and kill the Chimera, a beast with the heads of a lion, goat, and serpent", Requirements: map[string]int{"Chimera": 1}, Reward: 1500},
		{Name: "Wraith's Revenge", Description: "Put the Wraith to rest by finding and destroying the object that ties it to this world", Requirements: map[string]int{"Wraith": 1}, Reward: 1000},
		{Name: "Lich's Phylactery", Description: "Destroy the Lich's phylactery, the object that keeps it immortal", Requirements: map[string]int{"Lich": 1}, Reward: 2500},
		{Name: "Dragon's Nest", Description: "Kill the Zombie Dragon and its undead minions in their nest", Requirements: map[string]int{"Zombie Dragon": 1, "Zombie": 5}, Reward: 3000},
		{Name: "Cave Troll's Hoard", Description: "Raid the cave troll's hoard, stealing valuable treasures and killing the troll", Requirements: map[string]int{"Cave Troll": 1}, Reward: 2000},
	}
)
